let profile, activeTab = 'identity', dirty = false, busy = false;
const fields = document.querySelector('#fields');
const status = document.querySelector('#status');
const titles = { identity: ['Player identity', 'Give the person behind the games a voice.'], projects: ['Project select', 'Choose the worlds people discover first.'], loadout: ['Developer loadout', 'Tools, strengths, and the ideas behind your games.'], theme: ['Visual settings', 'Make the colors and motion feel like you.'] };
const esc = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const get = key => key.split('.').reduce((value, k) => value[k], profile);
const set = (key, value) => { const keys = key.split('.'); let target = profile; for (const k of keys.slice(0, -1)) target = target[k]; target[keys.at(-1)] = value; };
const field = (label, key, { area = false, max = 120, full = false, type = 'text' } = {}) => `<div class="field ${full ? 'full' : ''}"><label for="${key}">${label}</label>${area ? `<textarea id="${key}" data-key="${key}" maxlength="${max}">${esc(get(key))}</textarea>` : `<input id="${key}" data-key="${key}" type="${type}" maxlength="${max}" value="${esc(get(key))}" />`}</div>`;
function markDirty() { dirty = true; const n = document.querySelector('#unsaved'); n.textContent = 'Unsaved changes'; n.className = 'dirty'; }
function render() {
  document.querySelector('#page-title').textContent = titles[activeTab][0];
  document.querySelector('#page-description').textContent = titles[activeTab][1];
  document.querySelectorAll('nav button').forEach(b => b.classList.toggle('active', b.dataset.tab === activeTab));
  if (activeTab === 'identity') fields.innerHTML = `<h2>Player card</h2><div class="field-grid">${field('Display name', 'identity.name', { max: 48 })}${field('Callsign', 'identity.callsign', { max: 20 })}${field('Headline', 'identity.role', { max: 52, full: true })}${field('Tagline · first line', 'identity.tagline.0', { max: 24 })}${field('Tagline · second line', 'identity.tagline.1', { max: 24 })}${field('Location', 'identity.location', { max: 42 })}${field('Status', 'identity.status', { max: 80 })}${field('Current quest', 'identity.currentFocus', { max: 52, full: true })}${field('Short bio', 'identity.bio', { area: true, max: 700, full: true })}</div><h2>Where to find you</h2>${field('GitHub profile', 'links.github', { max: 500, type: 'url' })}${field('LinkedIn', 'links.linkedin', { max: 500, type: 'url' })}${field('Portfolio · optional', 'links.portfolio', { max: 500, type: 'url' })}${field('Public email · optional', 'links.email', { max: 100, type: 'email' })}<p class="help">These details appear in the public profile README. GitHub's sidebar bio and avatar are managed in GitHub settings.</p>`;
  if (activeTab === 'projects') fields.innerHTML = `<p class="help">Up to six projects. Tiles link to their repositories. Artwork is selectable; the café scene uses your game screenshot.</p>${profile.projects.map((p, i) => `<section class="project-block"><div class="project-top"><h2>0${i + 1} / ${esc(p.title)}</h2><button type="button" class="remove" data-remove="${i}">Remove</button></div><div class="field-grid">${field('Project title', `projects.${i}.title`, { max: 34 })}${field('Genre / category', `projects.${i}.genre`, { max: 30 })}${field('Unique ID', `projects.${i}.id`, { max: 40 })}<div class="field"><label for="art-${i}">Tile artwork</label><select id="art-${i}" data-key="projects.${i}.art">${['cafe', 'platformer', 'runner', 'jam'].map(art => `<option ${art === p.art ? 'selected' : ''}>${art}</option>`).join('')}</select></div>${field('Description', `projects.${i}.description`, { area: true, max: 130, full: true })}${field('Tools / technology', `projects.${i}.tech`, { max: 48, full: true })}${field('Repository URL', `projects.${i}.url`, { max: 500, type: 'url', full: true })}${field('Play URL · optional', `projects.${i}.playUrl`, { max: 500, type: 'url', full: true })}${field('Accent color', `projects.${i}.accent`, { max: 7 })}</div></section>`).join('')}<button type="button" id="add-project" class="secondary" ${profile.projects.length >= 6 ? 'disabled' : ''}>Add a project +</button>`;
  if (activeTab === 'loadout') fields.innerHTML = profile.loadout.map((s, i) => `<section class="loadout-block"><h2>0${i + 1} / Loadout</h2>${field('Category', `loadout.${i}.label`, { max: 24 })}${field('Tools / strength', `loadout.${i}.tools`, { max: 30 })}${field('What you do with them', `loadout.${i}.detail`, { max: 48 })}</section>`).join('') + `<h2>Design principles</h2>${profile.principles.map((s, i) => field(`Principle ${i + 1}`, `principles.${i}`, { max: 100 })).join('')}`;
  if (activeTab === 'theme') fields.innerHTML = `<h2>Color palette</h2><p class="help">Keep the main text bright and the background dark for readable tiles. Colors change after Save & build.</p>${Object.entries({ background: 'Background', surface: 'Panel surface', accent: 'Primary accent', secondary: 'Secondary accent', text: 'Main text', muted: 'Secondary text' }).map(([key, label]) => `<div class="field"><label for="color-${key}">${label}</label><div class="color-field"><input id="color-${key}" type="color" data-key="theme.${key}" value="${profile.theme[key]}" /><input aria-label="${label} hex code" type="text" data-key="theme.${key}" maxlength="7" value="${profile.theme[key]}" /></div></div>`).join('')}<h2>Motion</h2><div class="checkbox"><input id="animation" type="checkbox" data-key="theme.animation" ${profile.theme.animation ? 'checked' : ''} /><label for="animation">Animated hero · orbital world & portal</label></div><p class="help">Turn it off for a static header. Visitors who prefer reduced motion get the still image when their browser and GitHub honor the picture source.</p>`;
}
fields.addEventListener('input', event => { const key = event.target.dataset.key; if (!key) return; set(key, event.target.type === 'checkbox' ? event.target.checked : event.target.value); if (key.startsWith('theme.')) fields.querySelectorAll(`[data-key="${key}"]`).forEach(input => { if (input !== event.target && /^#[0-9a-f]{6}$/i.test(event.target.value)) input.value = event.target.value; }); markDirty(); });
fields.addEventListener('click', event => { const remove = event.target.dataset.remove; if (remove !== undefined) { if (profile.projects.length === 1) { status.textContent = 'Keep at least one project.'; return; } profile.projects.splice(Number(remove), 1); markDirty(); render(); } if (event.target.id === 'add-project') { const ids = new Set(profile.projects.map(p => p.id)); let n = 1; while (ids.has(`new-project-${n}`)) n++; profile.projects.push({ id: `new-project-${n}`, title: 'New project', genre: 'IN DEVELOPMENT', description: 'Describe the playable idea.', tech: 'Unity / C#', url: profile.links.github + '?tab=repositories', playUrl: '', art: 'platformer', accent: profile.theme.accent }); markDirty(); render(); } });
document.querySelectorAll('nav button').forEach(button => button.addEventListener('click', () => { activeTab = button.dataset.tab; render(); }));
document.querySelector('#profile-form').addEventListener('submit', event => event.preventDefault());
async function submit(publish = false) {
  if (busy) return; busy = true;
  document.querySelectorAll('button,input,textarea,select').forEach(b => b.disabled = true);
  status.className = ''; status.textContent = publish ? 'Building the artwork and publishing to GitHub…' : 'Saving the config and rendering the artwork…';
  try {
    const response = await fetch(publish ? '/api/publish' : '/api/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(profile) });
    const result = await response.json(); if (!response.ok) throw new Error(result.error);
    dirty = false; document.querySelector('#unsaved').textContent = 'All changes saved'; document.querySelector('#unsaved').className = '';
    document.querySelector('#preview').src = '/preview.html?v=' + Date.now();
    status.textContent = publish ? `Published to GitHub. Commit ${result.commit}.` : 'Saved and built. The preview is up to date; publish when ready.';
  } catch (error) { status.className = 'error'; status.textContent = error.message; } finally { busy = false; document.querySelectorAll('button').forEach(b => b.disabled = false); render(); }
}
document.querySelector('#save').addEventListener('click', () => submit());
document.querySelector('#publish').addEventListener('click', () => submit(true));
document.querySelector('#download').addEventListener('click', () => { const url = URL.createObjectURL(new Blob([JSON.stringify(profile, null, 2) + '\n'], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'profile.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); });
window.addEventListener('beforeunload', event => { if (dirty) { event.preventDefault(); event.returnValue = ''; } });
(async () => { try { const response = await fetch('/api/profile'); if (!response.ok) throw new Error('Could not load the profile.'); profile = await response.json(); render(); status.textContent = 'Connected to profile.json. Edit a section, then Save & build.'; } catch (error) { status.className = 'error'; status.textContent = error.message; document.querySelectorAll('#save,#publish,#download').forEach(b => b.disabled = true); } })();
